#!/bin/bash
echo "School"
Â^C
root@f37b6a4161e1:/alx-pre_course/0x01-git/bash# git add .
root@f37b6a4161e1:/alx-pre_course/0x01-git/bash# git commit -m "Starting to code today, no cool"

exit













































